#!/bin/sh

# This script builds the app for production release and sets the appropriate ENV vars
# for subsequent application running.

PROJ_DIR="$0"

echo "=== STARTING BUILD + DEPLOY SETUP!"

read -p "=== Which port will the app run on? " sel_port
export PORT=$sel_port

echo "=== Generating secret key base..."
export SECRET_KEY_BASE=$(mix phx.gen.secret)

echo "=== Getting dependencies..."
mix deps.get --only prod

echo "=== Compiling application..."
MIX_ENV=prod mix compile

echo "=== Building/Packaging assets..."
MIX_ENV=prod mix assets.deploy

echo "=== Creating production release..."
mix phx.gen.release --no-ecto

read -p "=== Clean up source files? [y/n] " answer

if [ "$answer" = "y" ]; then
    echo "=== Cleaning up source files..."
    cd ..
    rm -rf $PROJ_DIR
fi

echo "=== Production built successfully!"
