#!/bin/sh

# This script builds the app for production release and sets the appropriate ENV vars
# for subsequent application running.

PROD_NAME=$(pwd | xargs basename)_PROD
PROD_DIR=$(pwd | xargs dirname)/$PROD_NAME

echo ">>> STARTING BUILD + DEPLOY SETUP!"

read -p ">>> Which port will the app run on? " sel_port

echo ">>> Getting dependencies..."
mix deps.get

echo ">>> Compiling application..."
MIX_ENV=prod mix compile

echo ">>> Generating secret key base..."
SECRET_KEY_BASE=$(MIX_ENV=prod mix phx.gen.secret)

echo ">>> Building/Packaging assets..."
MIX_ENV=prod mix assets.deploy

echo ">>> Creating production release..."
mix phx.gen.release --no-ecto

MIX_ENV=prod mix release --path $PROD_DIR

# Setup app environment
echo "export PHX_SERVER=true" > $PROD_DIR/.env
echo "export PORT=$sel_port" >> $PROD_DIR/.env
echo -n "export SECRET_KEY_BASE=$SECRET_KEY_BASE" >> $PROD_DIR/.env

read -p ">>> Clean up source files? [y/n] " answer

if [ "$answer" = "y" ]; then
    echo ">>> Cleaning up source files..."
    SRC_DIR=$(pwd)
    cd ..
    rm -rf $SRC_DIR
fi

echo ">>> Production built successfully!"
